language: php

php:
 - 7.2
 - 7.3

before_script:
 - wget http://getcomposer.org/composer.phar
 - mkdir zoho_sync_auth
 - touch zcrm_oauthtokens.txt
 - touch ZCRMClientLibrary.log
 - wget -O 239515915463_33e7bbe532d1ec07802e_512.jpeg https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=200&q=80
 - php composer.phar install --dev --no-interaction

script:
 - phpunit

after_script:
 - php vendor/bin/coveralls -v
