version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-cli
    steps:
      - checkout
      # Init Zoho environment for API
      - run: mkdir -p client/logs
      - run: touch client/logs/ZCRMClientLibrary.log
      - run: chmod 757 client/logs/ZCRMClientLibrary.log
      - run: mkdir -p client/token
      - run: touch client/token/zcrm_oauthtokens.txt
      - run: sudo composer self-update
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: Run Unit Tests
          command: vendor/bin/phpunit
          environment:
            FILEPATH_TEST_UPLOAD: ~/project/.circleci/sample/zoho-logo-zh-2x.png
            APPLICATION_LOG_FILE_PATH: ~/project/client/logs
            TOKEN_PERSISTENCE_PATH: ~/project/client/token
            PERSISTENCE_HANDLER_CLASS: ZohoOAuthPersistenceByFile

workflows:
  Setup:
    jobs:
      - build
  version: 2