version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-cli
    enviroment:
      filepath_upload: ~/project/.circleci/sample/zoho-logo-zh-2x.png
      applicationLogFilePath: ~/project/code/client/logs
      token_persistence_path: ~/project/code/client/token
      persistence_handler_class: ZohoOAuthPersistenceByFile
    steps:
      - checkout
      # Init Zoho environment for API
      - run: mkdir -p client/logs
      - run: touch client/logs/ZCRMClientLibrary.log
      - run: mkdir -p client/token
      - run: touch client/token/zcrm_oauthtokens.txt
      - run: cat client/token/zcrm_oauthtokens.txt
      - run: sudo composer self-update
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: vendor/bin/phpunit

workflows:
  Setup:
    jobs:
      - build
  version: 2